# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'G-W1PYX136X2'

menu:
- {name: 'Blog',       url: 'blog'}
- {name: 'Documentation',      url: 'documentation'}
- {name: 'GPTs',      url: 'gpts'}
- {name: 'Playlist',      url: 'playlist'}
- {name: 'About',              url: 'about'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'x-twitter', link:    'https://x.com/singingsores'}
# - {icon: 'instagram', link:    'https://www.instagram.com/thesightofspira/'}
# - {icon: 'tumblr', link:    'https://kiyosawa.tumblr.com/'}
- {icon: 'github', link:    'https://github.com/spira-unplugged'}
- {icon: 'lastfm', link:    'https://www.last.fm/ja/user/realmofflight'}
- {icon: 'paypal', link:    'https://paypal.me/birusupi'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  previous_page: "Newer"
  next_page: "Older"

sharing_button_prompt: 'share'

related_posts: 'Related Posts'

post_date_prefix: 'Written on'
